server:
  # 端口
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cakeshow?useUnicode=true&characterEncoding=UTF-8
    uesrname: root
    password: root
    hikari:
      pool-name: DateHikariCP
      minium-idel: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1

# Mybatis-plus配置
mybatis-plus:
  mapper-location: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.wonderland.sserver.pojo
  configuration:
    map-underscore-to-camel-case: false

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: cakeShow-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800L
  # JWT 负载中拿到开头
  tokenHead: Bearer

